from support.registry import export_module as _export_module

_export_module(globals(), "support.db.alembic.foundation.module")
_export_module(globals(), "support.db.database.cleanup.dual.write.module")
_export_module(globals(), "support.db.database.lifecycle.module")
_export_module(globals(), "support.db.postgres.api.smoke.module")
_export_module(globals(), "support.db.requirements.fi.module")
_export_module(globals(), "support.postgres.legacy.connection.module")
_export_module(globals(), "support.postgres.legacy.save.module")
_export_module(globals(), "support.postgres.cutover.evidence.check.module")
_export_module(globals(), "support.postgres.cutover.gate.module")
_export_module(globals(), "support.postgres.cutover.script.it.gates.module")
_export_module(globals(), "support.postgres.migration.inventory.module")
_export_module(globals(), "support.postgres.rollback.check.module")
_export_module(globals(), "support.postgres.gate.module")
_export_module(globals(), "support.query.module")
_export_module(globals(), "support.reports.fi.module")
_export_module(globals(), "support.router.response.model.coverage.module")
_export_module(globals(), "support.user.check.module")
del _export_module
